In [1]:
import pandas as pd


# 模型阈值
SEQ_LEN = 5
MIN_GROUP_SIZE = 20
MAX_DURATION_SECONDS = 300
GROUP_DURATION_SECONDS = 3600
UTC_HOUR_START = 0 #5
UTC_HOUR_END = 23 #17

TESTMONTH = '202401'
TESTDAY = '20240102'

# prompt: 读取原始月份文件

# df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/500000.csv',index_col=0) # google driver

df = pd.read_csv('layer0/bak/'+TESTMONTH+'.csv',index_col=0)
df

In [2]:
# 读取黑样本
df_blacksample = pd.read_csv('layer0/initialList.txt', index_col=0,names=['SENDER_WALLET'])
df_blacksample

Empty DataFrame
Columns: []
Index: [0x000000000799a08e40de98f85f28aecea4e2c006, 0x00000002b7d3b2da5ce175347e2a7d265d740926, 0x0000000fe4e90789b4cfcd19be68bf3f5f075f22, 0x00000034a9ac3ee7b0a2cb2e5207dcfa1b998347, 0x00000039d07ce382d8d89fd144033869633d278e, 0x0000004af53658217abd341e94f4b0ac104731aa, 0x0000005996004acb4610599b8cd09476b7a5998f, 0x00000073972baddfe6c63f88ca1e3676e47249c0, 0x000000877ae0d90edab782f5596bc54ac08d4044, 0x0000009a16c98605d2d8c5d7ec219cb57637de3a, 0x000000a9606d03f89bae2c3f4d359f1bc4888eaa, 0x000000c96c57749948fd237ef6e4ee0a77ff1361, 0x000000f8fc0d45b5314b0de28ddd72f084f399de, 0x0000014fd09a8409877dbf6f4b473d17b25b859c, 0x0000023cbc437683aec074e3cb75ad38ae2e87e1, 0x000003aa283277d4ddae9821556483a1a7b5a436, 0x000005859f6e05e239f32f7f4880f9c42fff976e, 0x00000602c2b54fab4f6948bd24bdb7c5431e3475, 0x0000061f675ba189572cb6184b7be135a09725c5, 0x0000069ceda45cea5fff22fedd9f5a4cca3833a3, 0x000006a684b041c226b124eed38736a0433dc234, 0x000007dbb5ab1de83e51527ce53fda4ff5af79c9, 0x0000084397b6d03d925d3deeddea90edb4f073b4, 0x0000086bf77af45a5ccdc3fef39a9985c84f1b63, 0x000008ae71199035a5fd01d90717f4720008b89a, 0x0000092067aa2177393ac24a7fdc046ba5406c84, 0x00000939ccc87eb86f949d5cb33cfd7ecf2e21b7, 0x00000faf9d5995b73d962e24b59a5069febb7c6f, 0x000013f1452f99f98772788d41b1d218b8b3fe51, 0x0000149e0da94f279a2bf9695dd1a6dddde6426f, 0x00001785d3eeab284def7d8418464ecbfb98e391, 0x00001f5b325878d5e6fb2d87bc3b13852fbf3edf, 0x00002ccf30cae88ee2eb84da0c4e0f15534aad90, 0x000037128f641cdafc75ad0a8c8907c98b87407b, 0x00003d252f02dfa26059c8670a4316c011846318, 0x00003fcfbec57956defa036dc4a5b110a82ff201, 0x000048a3c1d371e9856c54eaf65fe16f9e19e0e9, 0x00004b8359d4ebddf8a50f985b91ad5f87092670, 0x0000529d701b3537649a33be933dea8f46922c70, 0x00005fab4df6b1c4a3eb5cf7db357cd766c65991, 0x000060c30cfd6a51087eeca22b42913f04e01236, 0x000061e044b789dfc5d1e6499ff11fe1024cbe07, 0x000062b2b488d32f3f64874872e5b50c4ab60fa2, 0x00006616246240db5e93571b8dff997fb4b5933d, 0x000068a3c302c8c0277ac2a6e3961e7d2ee853da, 0x00007013ea2dd903bcc73ac11104e6b580528f89, 0x000081050c7c5fe83f3415c255ddfe0092c9714c, 0x00008d4783086d1a37101983c5cbe15e04c942c0, 0x000091b999bc6bb0f2b1a1369f9eff5c8c22a2d4, 0x000098a57816e06e103230ef584d6a7fa6050b89, 0x0000a98a6caa48cc8fd665ad32bcac9a5599791f, 0x0000b1bd5172a08199f096f708c59761531b3ad9, 0x0000b735eced9249c446dad3b77b6dee09b33f9f, 0x0000bdff8af240ec07cc67614c2c858cd6e8318d, 0x0000bfb121750297accbf83e36d6881dbe408431, 0x0000c2fa36a052b4d198b8ea7d4c279ae8d89ba8, 0x0000c35d5c775b2ff8c19cb2956aab49a15647c1, 0x0000c749def51373929751146b8c885703af42a4, 0x0000d8a404e7edeede4687713442dcc7f60f1729, 0x0000e17c6000b10f037f1bcc4f3731d18a979e1a, 0x0000e7dcd85caa9fe419782d879ab9add65cc974, 0x0000eb200de956781a2d7d9d6ae00d1d041872ea, 0x0000ebce74b02f4f3922e5eaf2abf3e70f20d058, 0x0000f47806491a0edbf8ed8cf0a1f6c9674f9704, 0x0000f80afecf2d58d0864033217a7dd2dfd87bac, 0x0001004acffc3541256c309f76fc4c2317598e39, 0x000105fac5fc1680c38670ddcbb0b7b9c889c261, 0x000116b6e5cca3a92d89b187388393484b098700, 0x000119902eea3d12837ffe38c7c5d1da71ed66d6, 0x00012429f82e64a074ddeeda60745c34ce9f9e4e, 0x000126c40021aa178f232373d70afd7f4d8974c0, 0x0001272048346c34e09a64d02c3a0a5b8f96a874, 0x0001480edb3b80780d1a2e9230d34fea8237c020, 0x00014d84a936f34b27417aad44447bfe22382bd4, 0x00014f714f7dfccc9835098a95340fae9555bef9, 0x00015e4a04eee3dfb417a322262fd3c0f150b25a, 0x0001680e0ccf437486df30b925bf3749af0f4243, 0x00016b684cc9b64b6a3f756c5cb5ac988ebb8a31, 0x00016d5723aabd80498ed00c4f02e4e45d67c093, 0x00018a13a09c247b836e33910404443e5fde67bf, 0x000198c8744dc5c46ffae8c82b98a366a0132690, 0x0001a6e30338391d9acfffaf1bf6a4cc1fa4f394, 0x0001a8e45e25761b4f3358bb0d255a664b7e34d2, 0x0001b4ec169463f8567ca77770fbb71c077bd29c, 0x0001b56624c596845dcfb0f6f94d871afecd6d17, 0x0001ca4e891a5b4738ea28f5a9724b1fa53a1839, 0x0001d1c2d49e7d8c970f87a48203c15972b13dec, 0x0001dcfa75278b8a5f5464b9ae9200053580bb34, 0x0001e3f56b033cc7f1252b978ee1b2dbddaadc73, 0x0001e9123c5d0a009fe4fd15ac907eb2a4c7c278, 0x0001ef9eb191e8c75b0db3f6b17f1ad5cbc90b8b, 0x0001f71a48422ad1e59a411b08e5798ca90044f0, 0x0001ff0fa2c232c86884e37e1835f5fafffb10d7, 0x000206f7289fa4c8bfc0308884c022e007c7479b, 0x00020de47ddea35b8ae187a73a1b4415b6621afa, 0x00021682c064067cd72da97824b91ee136143040, 0x0002173e80d30cf302f37c6c10ffea9b39066eb5, 0x00021c6201a4e5652d107cf9b9141ad80bc06b1b, 0x0002280a6a14fc309cf889019bc2a131ba9de775, 0x00022e151aa333a5c6d2dd150bbbdbe1548a360e, ...]

[803093 rows x 0 columns]

In [3]:
##定义函数process_one_day(df,day),输入YYYYMMDD格式，截取SOURCE_TIMESTAMP_UTC字段5AM-17PM的数据
def process_one_day(df, day):
  """
  Extracts data from the specified day and time range.

  Args:
      df: Pandas DataFrame containing the data.
      day: String in YYYYMMDD format representing the target day.

  Returns:
      Pandas DataFrame containing the filtered data.
  """

  # Convert the day string to datetime format
  day_datetime = pd.to_datetime(day)

  # Convert the SOURCE_TIMESTAMP_UTC column to datetime format
  df['SOURCE_TIMESTAMP_UTC'] = pd.to_datetime(df['SOURCE_TIMESTAMP_UTC'])

  # Create a boolean mask to filter data between 5am and 5pm
  mask = (df['SOURCE_TIMESTAMP_UTC'].dt.hour >= UTC_HOUR_START) & (df['SOURCE_TIMESTAMP_UTC'].dt.hour <= UTC_HOUR_END ) & (df['SOURCE_TIMESTAMP_UTC'].dt.date == day_datetime.date())

  # Filter the DataFrame based on the mask
  filtered_df = df[mask].reset_index()

  return filtered_df

# day_df = process_one_day(df,TESTDAY)
# day_df

In [4]:
def derive_event_amount(df):
  """
  Creates a new event_name column and calculates the sum of two columns for each row in the DataFrame.

  Args:
      df (pd.DataFrame): DataFrame containing the data.

  Returns:
      pd.DataFrame: DataFrame with new columns "event_name" and "amount".
  """

  df["event_name"] = df.apply(lambda row: "-".join([
      str(row["SOURCE_CHAIN"]),
      # str(row["SOURCE_CONTRACT"]),
      str(row["PROJECT"]),
      str(row["DESTINATION_CHAIN"]),
      # str(row["DESTINATION_CONTRACT"]),
  ]), axis=1)

  # df["amount"] = df.apply(lambda row: row["NATIVE_DROP_USD"] + row["STARGATE_SWAP_USD"], axis=1)
  df["amount"] = df["NATIVE_DROP_USD"].fillna(0) + df["STARGATE_SWAP_USD"].fillna(0)
  return df

# Apply the function to the DataFrame


# day_df = derive_event_amount(day_df)
# day_df = day_df[['SENDER_WALLET','event_name','amount','SOURCE_TIMESTAMP_UTC',]]
# print(day_df.shape)
# day_df

In [5]:
# prompt: check_user_rawdata(df,sender):该函数输出指定账号按SOURCE_TIMESTAMP_UTC时间排序的记录

def check_user_rawdata(df, sender):
  """
  Filters the DataFrame to show only records for a specific sender, sorted by SOURCE_TIMESTAMP_UTC.

  Args:
      df (pd.DataFrame): DataFrame containing the data.
      sender (str): Address of the sender to filter for.

  Returns:
      pd.DataFrame: Filtered DataFrame containing only records for the specified sender.
  """

  user_df = df[df["SENDER_WALLET"] == sender].sort_values(by="SOURCE_TIMESTAMP_UTC")
  return user_df

# # Example usage
# sender = "0xc4460b4fab400225bd8065bc3d9c092ff7eacdb5"
# user_df = check_user_rawdata(df, sender)
# # user_df = check_user_rawdata(day_df, sender)
# user_df

In [6]:
# check_user_rawdata(day_df, sender)

## 生成序列

In [7]:
%time
# prompt: 定义窗口函数sender_seq(df,seq_len)，按sender分组丢弃记录数<seq_len的sender，然后将每个sender的event_name按时间排序，使用分号拼接为长度为seq_len的序列字符串seq_N，其它新增字段包括duration=endtime-starttime，total_amt = sum(amount)，输出数据集应该和原始数据集行数相同，增加了3列；


def sender_seq(df,seq_len):
  """
  This function groups the DataFrame by sender and processes sequences of events based on the specified sequence length.

  Args:
      df (pd.DataFrame): DataFrame containing the data.
      seq_len (int): Sequence length to consider.

  Returns:
      pd.DataFrame: Transformed DataFrame with additional sequence-based features.
  """

  sender_grouped = df.groupby('SENDER_WALLET')

  result_list = []
  for sender, group_df in sender_grouped:
    # Filter groups with insufficient data points
    if len(group_df) < seq_len:
      continue

    # Sort events by timestamp within each group
    group_df = group_df.sort_values(by='SOURCE_TIMESTAMP_UTC')

    # Initialize variables
    seq_list = []
    duration = 0
    total_amt = 0

    # Process events within the sequence length
    for i in range(0, len(group_df) - seq_len + 1):
      seq_str = ";".join(group_df['event_name'].iloc[i:i+seq_len])
      seq_list.append(seq_str)

      # Calculate duration and total amount for the sequence
      start_time = group_df['SOURCE_TIMESTAMP_UTC'].iloc[i]
      end_time = group_df['SOURCE_TIMESTAMP_UTC'].iloc[i+seq_len-1]
      duration = end_time - start_time
      total_amt = group_df['amount'].iloc[i:i+seq_len].sum()

      # Create a new row with sequence information
      new_row = {
          'SENDER_WALLET': sender,
          'seq_N': seq_str,
          'duration': duration,
          'start_time': start_time,
          'total_amt': total_amt
      }
      result_list.append(new_row)

  # Create a new DataFrame from the processed data
  seq_df = pd.DataFrame(result_list)

  return seq_df

# # Apply the function to the DataFrame
# seq_df = sender_seq(day_df, SEQ_LEN)
# print(seq_df.shape)
# seq_df

Wall time: 0 ns

In [8]:
%%time
# prompt: duplicate_first_seq(seq_df), seq过滤时长和金额，针对每个sender相同的seq_N只保留第一条记录

def duplicate_first_seq(seq_df):
  """
  Removes duplicate sequences for each sender, keeping only the first occurrence.

  Args:
      seq_df (pd.DataFrame): DataFrame containing the sequences.

  Returns:
      pd.DataFrame: DataFrame with duplicate sequences removed.
  """
  seq_df = seq_df[(seq_df['duration'].dt.total_seconds()<=MAX_DURATION_SECONDS) \
#                   & (seq_df['total_amt']>0)
                 ]
  # Group by sender and sequence
  grouped_df = seq_df.groupby(['SENDER_WALLET', 'seq_N'])

  # Keep only the first row for each group
  deduplicated_df = grouped_df.head(1)

  return deduplicated_df

# # Apply the function to the DataFrame
# deduplicated_df = duplicate_first_seq(seq_df)

# print(deduplicated_df.shape)
# deduplicated_df

Wall time: 0 ns

## 筛选聚集簇

In [9]:
%%time
# prompt: 定义筛选函数group_filter(deduplicated_df, group_size,duration)，先按seq_N分组输出sender数>=group_size的组，中间结果df_filter_group包括输出列[seq_N,group_size,avg_duration]，然后用中间结果df_filter_group和原始数据集deduplicated_df内连接得到最终结果；

def group_filter(deduplicated_df, min_group_size,max_duration):

  # Group sequences by seq_N and count sender wallets
  grouped_df = deduplicated_df.groupby('seq_N').agg(group_size=('SENDER_WALLET', 'nunique'), \
                                                    group_start_time=('start_time', 'min'), \
                                                    group_end_time=('start_time', 'max'), \
                                                    group_avg_amt=('total_amt', 'mean'), \
#                            group_avg_duration=('duration', lambda x: x.dt.total_seconds().mean()) \
                                                   )
  grouped_df['group_duration'] = grouped_df['group_end_time'] - grouped_df['group_start_time']

  # Filter groups based on group size and average duration
  df_filter_group = grouped_df[(grouped_df['group_size'] >= min_group_size) \
#                                & (grouped_df['group_duration'].dt.total_seconds() <= max_duration)
                              ]

  # Merge filtered groups with original data based on seq_N
  result_df = pd.merge(deduplicated_df, df_filter_group, on='seq_N')

  return result_df

# # Apply the function with desired parameters
# filtered_df = group_filter(deduplicated_df, min_group_size=MIN_GROUP_SIZE, max_duration=GROUP_DURATION_SECONDS)

# # Print the filtered DataFrame
# print(filtered_df.shape)
# filtered_df

Wall time: 0 ns

## 处理某日/ 某周期 数据结果存到文件

In [10]:
%%time
def process_daily_rst(df,dt='20240101'):
    day_df = process_one_day(df,dt)
    day_df = derive_event_amount(day_df)
    day_df = day_df[['SENDER_WALLET','event_name','amount','SOURCE_TIMESTAMP_UTC',]]
    seq_df = sender_seq(day_df, SEQ_LEN)
    deduplicated_df = duplicate_first_seq(seq_df)
    filtered_df = group_filter(deduplicated_df, min_group_size=MIN_GROUP_SIZE, max_duration=GROUP_DURATION_SECONDS)
    filtered_df['dt'] = dt
#     filtered_df.to_csv(f'layer0/rst/{dt}.csv')
    print(f'save_daily_rst {dt} finish!')
    return filtered_df

# df = pd.read_csv('layer0/bak/202401.csv',index_col=0)
# df

# rst_testday = save_daily_rst(df,dt=TESTDAY)
# rst_testday

Wall time: 0 ns

In [11]:
%%time
# prompt: 定义函数save_batch_rst(df,start_date,end_date)，根据输入的起始结束日期循环调用save_daily_rst(df,dt='20240101')函数处理每日结果daily_rst，将每日结果合并成一个batch_rst，存入文件名{start_date}_batch_{end_date}.csv

def save_batch_rst(df,start_date,end_date):
  date_list = [start_date]
  while date_list[-1] != end_date:
    next_date = str(int(date_list[-1]) + 1)
    date_list.append(next_date)
  batch_rst = pd.DataFrame()
  for dt in date_list:
    daily_rst = process_daily_rst(df,dt)
    batch_rst = pd.concat([batch_rst,daily_rst])
  batch_rst.to_csv(f"layer0/rst/{start_date}_batch_{end_date}.csv",index=False)


def month_save_batch_rst(month_file,start_date,end_date):
  df = pd.read_csv(month_file,index_col=0)    
  date_list = [start_date]
  while date_list[-1] != end_date:
    next_date = str(int(date_list[-1]) + 1)
    date_list.append(next_date)
  batch_rst = pd.DataFrame()
  for dt in date_list:
    daily_rst = process_daily_rst(df,dt)
    batch_rst = pd.concat([batch_rst,daily_rst])
  batch_rst.to_csv(f"layer0/rst/{start_date}_batch_{end_date}.csv",index=False)

# batch_rst_202305 = month_save_batch_rst('layer0/bak/202305.csv','20230501','20230531')
# batch_rst_202305
# batch_rst_202401 = month_save_batch_rst('layer0/bak/202401.csv','20240101','20240131')
# batch_rst_202401

Wall time: 0 ns

In [16]:
%%time
month_save_batch_rst('layer0/bak/202306.csv','20230601','20230630')
month_save_batch_rst('layer0/bak/202307.csv','20230701','20230731')
month_save_batch_rst('layer0/bak/202308.csv','20230801','20230831')
month_save_batch_rst('layer0/bak/202309.csv','20230901','20230930')
month_save_batch_rst('layer0/bak/202310.csv','20231001','20231031')
month_save_batch_rst('layer0/bak/202311.csv','20231101','20231130')
month_save_batch_rst('layer0/bak/202312.csv','20231201','20231231')

save_daily_rst 20230601 finish!
save_daily_rst 20230602 finish!
save_daily_rst 20230603 finish!
save_daily_rst 20230604 finish!
save_daily_rst 20230605 finish!
save_daily_rst 20230606 finish!
save_daily_rst 20230607 finish!
save_daily_rst 20230608 finish!
save_daily_rst 20230609 finish!
save_daily_rst 20230610 finish!
save_daily_rst 20230611 finish!
save_daily_rst 20230612 finish!
save_daily_rst 20230613 finish!
save_daily_rst 20230614 finish!
save_daily_rst 20230615 finish!
save_daily_rst 20230616 finish!
save_daily_rst 20230617 finish!
save_daily_rst 20230618 finish!
save_daily_rst 20230619 finish!
save_daily_rst 20230620 finish!
save_daily_rst 20230621 finish!
save_daily_rst 20230622 finish!
save_daily_rst 20230623 finish!
save_daily_rst 20230624 finish!
save_daily_rst 20230625 finish!
save_daily_rst 20230626 finish!
save_daily_rst 20230627 finish!
save_daily_rst 20230628 finish!
save_daily_rst 20230629 finish!
save_daily_rst 20230630 finish!
save_daily_rst 20230701 finish!
save_daily_rst 20230702 finish!
save_daily_rst 20230703 finish!
save_daily_rst 20230704 finish!
save_daily_rst 20230705 finish!
save_daily_rst 20230706 finish!
save_daily_rst 20230707 finish!
save_daily_rst 20230708 finish!
save_daily_rst 20230709 finish!
save_daily_rst 20230710 finish!
save_daily_rst 20230711 finish!
save_daily_rst 20230712 finish!
save_daily_rst 20230713 finish!
save_daily_rst 20230714 finish!
save_daily_rst 20230715 finish!
save_daily_rst 20230716 finish!
save_daily_rst 20230717 finish!
save_daily_rst 20230718 finish!
save_daily_rst 20230719 finish!
save_daily_rst 20230720 finish!
save_daily_rst 20230721 finish!
save_daily_rst 20230722 finish!
save_daily_rst 20230723 finish!
save_daily_rst 20230724 finish!
save_daily_rst 20230725 finish!
save_daily_rst 20230726 finish!
save_daily_rst 20230727 finish!
save_daily_rst 20230728 finish!
save_daily_rst 20230729 finish!
save_daily_rst 20230730 finish!
save_daily_rst 20230731 finish!
save_daily_rst 20230801 finish!
save_daily_rst 20230802 finish!
save_daily_rst 20230803 finish!
save_daily_rst 20230804 finish!
save_daily_rst 20230805 finish!
save_daily_rst 20230806 finish!
save_daily_rst 20230807 finish!
save_daily_rst 20230808 finish!
save_daily_rst 20230809 finish!
save_daily_rst 20230810 finish!
save_daily_rst 20230811 finish!
save_daily_rst 20230812 finish!
save_daily_rst 20230813 finish!
save_daily_rst 20230814 finish!
save_daily_rst 20230815 finish!
save_daily_rst 20230816 finish!
save_daily_rst 20230817 finish!
save_daily_rst 20230818 finish!
save_daily_rst 20230819 finish!
save_daily_rst 20230820 finish!
save_daily_rst 20230821 finish!
save_daily_rst 20230822 finish!
save_daily_rst 20230823 finish!
save_daily_rst 20230824 finish!
save_daily_rst 20230825 finish!
save_daily_rst 20230826 finish!
save_daily_rst 20230827 finish!
save_daily_rst 20230828 finish!
save_daily_rst 20230829 finish!
save_daily_rst 20230830 finish!
save_daily_rst 20230831 finish!
save_daily_rst 20230901 finish!
save_daily_rst 20230902 finish!
save_daily_rst 20230903 finish!
save_daily_rst 20230904 finish!
save_daily_rst 20230905 finish!
save_daily_rst 20230906 finish!
save_daily_rst 20230907 finish!
save_daily_rst 20230908 finish!
save_daily_rst 20230909 finish!
save_daily_rst 20230910 finish!
save_daily_rst 20230911 finish!
save_daily_rst 20230912 finish!
save_daily_rst 20230913 finish!
save_daily_rst 20230914 finish!
save_daily_rst 20230915 finish!
save_daily_rst 20230916 finish!
save_daily_rst 20230917 finish!
save_daily_rst 20230918 finish!
save_daily_rst 20230919 finish!
save_daily_rst 20230920 finish!
save_daily_rst 20230921 finish!
save_daily_rst 20230922 finish!
save_daily_rst 20230923 finish!
save_daily_rst 20230924 finish!
save_daily_rst 20230925 finish!
save_daily_rst 20230926 finish!
save_daily_rst 20230927 finish!
save_daily_rst 20230928 finish!
save_daily_rst 20230929 finish!
save_daily_rst 20230930 finish!
save_daily_rst 20231001 finish!
save_daily_rst 20231002 finish!
save_daily_rst 20231003 finish!
save_daily_rst 20231004 finish!
save_daily_rst 20231005 finish!
save_daily_rst 20231006 finish!
save_daily_rst 20231007 finish!
save_daily_rst 20231008 finish!
save_daily_rst 20231009 finish!
save_daily_rst 20231010 finish!
save_daily_rst 20231011 finish!
save_daily_rst 20231012 finish!
save_daily_rst 20231013 finish!
save_daily_rst 20231014 finish!
save_daily_rst 20231015 finish!
save_daily_rst 20231016 finish!
save_daily_rst 20231017 finish!
save_daily_rst 20231018 finish!
save_daily_rst 20231019 finish!
save_daily_rst 20231020 finish!
save_daily_rst 20231021 finish!
save_daily_rst 20231022 finish!
save_daily_rst 20231023 finish!
save_daily_rst 20231024 finish!
save_daily_rst 20231025 finish!
save_daily_rst 20231026 finish!
save_daily_rst 20231027 finish!
save_daily_rst 20231028 finish!
save_daily_rst 20231029 finish!
save_daily_rst 20231030 finish!
save_daily_rst 20231031 finish!
save_daily_rst 20231101 finish!
save_daily_rst 20231102 finish!
save_daily_rst 20231103 finish!
save_daily_rst 20231104 finish!
save_daily_rst 20231105 finish!
save_daily_rst 20231106 finish!
save_daily_rst 20231107 finish!
save_daily_rst 20231108 finish!
save_daily_rst 20231109 finish!
save_daily_rst 20231110 finish!
save_daily_rst 20231111 finish!
save_daily_rst 20231112 finish!
save_daily_rst 20231113 finish!
save_daily_rst 20231114 finish!
save_daily_rst 20231115 finish!
save_daily_rst 20231116 finish!
save_daily_rst 20231117 finish!
save_daily_rst 20231118 finish!
save_daily_rst 20231119 finish!
save_daily_rst 20231120 finish!
save_daily_rst 20231121 finish!
save_daily_rst 20231122 finish!
save_daily_rst 20231123 finish!
save_daily_rst 20231124 finish!
save_daily_rst 20231125 finish!
save_daily_rst 20231126 finish!
save_daily_rst 20231127 finish!
save_daily_rst 20231128 finish!
save_daily_rst 20231129 finish!
save_daily_rst 20231130 finish!
save_daily_rst 20231201 finish!
save_daily_rst 20231202 finish!
save_daily_rst 20231203 finish!
save_daily_rst 20231204 finish!
save_daily_rst 20231205 finish!
save_daily_rst 20231206 finish!
save_daily_rst 20231207 finish!
save_daily_rst 20231208 finish!
save_daily_rst 20231209 finish!
save_daily_rst 20231210 finish!
save_daily_rst 20231211 finish!
save_daily_rst 20231212 finish!
save_daily_rst 20231213 finish!
save_daily_rst 20231214 finish!
save_daily_rst 20231215 finish!
save_daily_rst 20231216 finish!
save_daily_rst 20231217 finish!
save_daily_rst 20231218 finish!
save_daily_rst 20231219 finish!
save_daily_rst 20231220 finish!
save_daily_rst 20231221 finish!
save_daily_rst 20231222 finish!
save_daily_rst 20231223 finish!
save_daily_rst 20231224 finish!
save_daily_rst 20231225 finish!
save_daily_rst 20231226 finish!
save_daily_rst 20231227 finish!
save_daily_rst 20231228 finish!
save_daily_rst 20231229 finish!
save_daily_rst 20231230 finish!
save_daily_rst 20231231 finish!
Wall time: 2h 35min 11s

In [17]:
%%time
month_save_batch_rst('layer0/bak/202402.csv','20240201','20240229')
month_save_batch_rst('layer0/bak/202403.csv','20240301','20240331')
month_save_batch_rst('layer0/bak/202404.csv','20240401','20240430')

save_daily_rst 20240201 finish!
save_daily_rst 20240202 finish!
save_daily_rst 20240203 finish!
save_daily_rst 20240204 finish!
save_daily_rst 20240205 finish!
save_daily_rst 20240206 finish!
save_daily_rst 20240207 finish!
save_daily_rst 20240208 finish!
save_daily_rst 20240209 finish!
save_daily_rst 20240210 finish!
save_daily_rst 20240211 finish!
save_daily_rst 20240212 finish!
save_daily_rst 20240213 finish!
save_daily_rst 20240214 finish!
save_daily_rst 20240215 finish!
save_daily_rst 20240216 finish!
save_daily_rst 20240217 finish!
save_daily_rst 20240218 finish!
save_daily_rst 20240219 finish!
save_daily_rst 20240220 finish!
save_daily_rst 20240221 finish!
save_daily_rst 20240222 finish!
save_daily_rst 20240223 finish!
save_daily_rst 20240224 finish!
save_daily_rst 20240225 finish!
save_daily_rst 20240226 finish!
save_daily_rst 20240227 finish!
save_daily_rst 20240228 finish!
save_daily_rst 20240229 finish!
save_daily_rst 20240301 finish!
save_daily_rst 20240302 finish!
save_daily_rst 20240303 finish!
save_daily_rst 20240304 finish!
save_daily_rst 20240305 finish!
save_daily_rst 20240306 finish!
save_daily_rst 20240307 finish!
save_daily_rst 20240308 finish!
save_daily_rst 20240309 finish!
save_daily_rst 20240310 finish!
save_daily_rst 20240311 finish!
save_daily_rst 20240312 finish!
save_daily_rst 20240313 finish!
save_daily_rst 20240314 finish!
save_daily_rst 20240315 finish!
save_daily_rst 20240316 finish!
save_daily_rst 20240317 finish!
save_daily_rst 20240318 finish!
save_daily_rst 20240319 finish!
save_daily_rst 20240320 finish!
save_daily_rst 20240321 finish!
save_daily_rst 20240322 finish!
save_daily_rst 20240323 finish!
save_daily_rst 20240324 finish!
save_daily_rst 20240325 finish!
save_daily_rst 20240326 finish!
save_daily_rst 20240327 finish!
save_daily_rst 20240328 finish!
save_daily_rst 20240329 finish!
save_daily_rst 20240330 finish!
save_daily_rst 20240331 finish!
save_daily_rst 20240401 finish!
save_daily_rst 20240402 finish!
save_daily_rst 20240403 finish!
save_daily_rst 20240404 finish!
save_daily_rst 20240405 finish!
save_daily_rst 20240406 finish!
save_daily_rst 20240407 finish!
save_daily_rst 20240408 finish!
save_daily_rst 20240409 finish!
save_daily_rst 20240410 finish!
save_daily_rst 20240411 finish!
save_daily_rst 20240412 finish!
save_daily_rst 20240413 finish!
save_daily_rst 20240414 finish!
save_daily_rst 20240415 finish!
save_daily_rst 20240416 finish!
save_daily_rst 20240417 finish!
save_daily_rst 20240418 finish!
save_daily_rst 20240419 finish!
save_daily_rst 20240420 finish!
save_daily_rst 20240421 finish!
save_daily_rst 20240422 finish!
save_daily_rst 20240423 finish!
save_daily_rst 20240424 finish!
save_daily_rst 20240425 finish!
save_daily_rst 20240426 finish!
save_daily_rst 20240427 finish!
save_daily_rst 20240428 finish!
save_daily_rst 20240429 finish!
save_daily_rst 20240430 finish!
Wall time: 57min 53s

## 多天csv结果，合并处理

%%time
# prompt: combine_mutipile_days(rst_dir): 读取指定目录下的所有csv文件合并成一个combine_df,csv第一行为列名（SENDER_WALLET	seq_N	duration	start_time	total_amt	group_size	group_start_time	group_end_time	group_avg_amt	group_duration	dt
# ）；然后输出结果数据集mutiple_days_rst_df，包括SENDER_WALLET以及SENDER_WALLET出现的dt的nunique个数，列名为dt_nunique

import pandas as pd
import os

def combine_mutipile_days(rst_dir):
  file_list = os.listdir(rst_dir)
  combine_df = pd.DataFrame()
  for file in file_list:
    if file.endswith(".csv"):
      file_path = os.path.join(rst_dir, file)
      df = pd.read_csv(file_path)
      combine_df = pd.concat([combine_df, df])
  combine_df.drop_duplicates(inplace=True)
  mutiple_days_rst_df = combine_df.groupby("SENDER_WALLET").agg({"dt": "nunique"}).rename(columns={"dt": "dt_nunique"}).reset_index()
  return mutiple_days_rst_df

check_sybil_ratio(mutiple_days_rst_df, 'layer0/batch_match.csv')

In [40]:
%%time
# prompt: combine_event_mutipile_days(rst_dir): 读取指定目录下的所有csv文件合并成一个combine_df,csv第一行为列名（SENDER_WALLET	seq_N	duration	start_time	total_amt	group_size	group_start_time	group_end_time	group_avg_amt	group_duration	dt
# ）；然后输出结果数据集mutiple_days_rst_df，包括SENDER_WALLET,event,以及按这两个字段聚合dt的nunique个数，列名为dt_nunique

import pandas as pd
import os

# 1.序列+钱包 天数相同、收尾日期重合 ，定义 group_key_list
# 2.序列+钱包 group_size再次筛选；
# 3.取用户的首个符合条件的序列为序列，保证用户不重复；

def user_unique_first_seq(mutiple_days_event_rst_df):
    mutiple_days_event_rst_df = mutiple_days_event_rst_df.sort_values(by='life_start_time')
    group_df = mutiple_days_event_rst_df.groupby(['SENDER_WALLET'])
    user_unique_first_seq = group_df.head(1)
    return user_unique_first_seq


def combine_event_mutipile_days(rst_dir):
  file_list = os.listdir(rst_dir)
  combine_df = pd.DataFrame()
  for file in file_list:
    if file.endswith(".csv"):
      file_path = os.path.join(rst_dir, file)
      df = pd.read_csv(file_path)
      combine_df = pd.concat([combine_df, df])
  combine_df.drop_duplicates(inplace=True)

  combine_df['start_date'] = pd.to_datetime(combine_df['start_time'], format='%Y-%m-%d %H:%M:%S').dt.normalize()
  combine_df['start_hour'] = pd.to_datetime(combine_df['start_time'], format='%Y-%m-%d %H:%M:%S').dt.floor('H')

  mutiple_days_rst_df = combine_df.groupby(["SENDER_WALLET","seq_N"]).agg(dt_nunique =("dt", "nunique"), \
                                                                          life_start_time = ("start_time","min"), \
                                                                          life_end_time = ("start_time","max"), \
                                                                          
                                                                          life_start_hour = ("start_hour","min"), \
                                                                          life_end_hour = ("start_hour","max"), \
                                                                          seq_daily_amount = ("total_amt","mean"), \
                                                                                                   ).reset_index()    
  mutiple_days_rst_df = mutiple_days_rst_df[mutiple_days_rst_df['dt_nunique']>1]    
#   mutiple_days_rst_df = combine_df.groupby(["SENDER_WALLET","seq_N"]).agg({"dt": "nunique"}).rename(columns={"dt": "dt_nunique"}).reset_index()
  group_key_list = ["seq_N","dt_nunique","life_start_hour","life_end_hour"]
  grouped_df = mutiple_days_rst_df.groupby(group_key_list).agg(final_group_size=("SENDER_WALLET","nunique")).reset_index()
  grouped_df['group_id'] = grouped_df.index
  df_filter_group = grouped_df[(grouped_df['final_group_size'] >= MIN_GROUP_SIZE)]


  result_df = pd.merge(mutiple_days_rst_df, df_filter_group, on=group_key_list)
  
#   result_df = user_unique_first_seq(result_df)

  return result_df

mutiple_days_event_rst_df = combine_event_mutipile_days('layer0/rst/')
mutiple_days_event_rst_df

Wall time: 2min

,SENDER_WALLET,seq_N,dt_nunique,life_start_time,life_end_time,life_start_hour,life_end_hour,seq_daily_amount,final_group_size,group_id
0,0x00389e78c3c5a2c5485ba8756601c8c843126573,DFK-DeFi Kingdoms-Klaytn Mainnet Cypress;DFK-D...,2,2024-01-13 15:25:35,2024-01-15 07:48:36,2024-01-13 15:00:00,2024-01-15 07:00:00,0.0,193,17223
1,0x00f889cfaf657db097d5a16da53fbbb03515f8a8,DFK-DeFi Kingdoms-Klaytn Mainnet Cypress;DFK-D...,2,2024-01-13 15:22:25,2024-01-15 07:44:52,2024-01-13 15:00:00,2024-01-15 07:00:00,0.0,193,17223
2,0x027b9dd7b0585a769ebd133ba391afcd686d9949,DFK-DeFi Kingdoms-Klaytn Mainnet Cypress;DFK-D...,2,2024-01-13 15:00:16,2024-01-15 07:37:10,2024-01-13 15:00:00,2024-01-15 07:00:00,0.0,193,17223
3,0x0701c0a252ac5e506106f42746a68dfb6cd87e6b,DFK-DeFi Kingdoms-Klaytn Mainnet Cypress;DFK-D...,2,2024-01-13 15:23:30,2024-01-15 07:46:24,2024-01-13 15:00:00,2024-01-15 07:00:00,0.0,193,17223
4,0x07894ee788ab6666157102fc93989040990c08b3,DFK-DeFi Kingdoms-Klaytn Mainnet Cypress;DFK-D...,2,2024-01-13 15:01:17,2024-01-15 07:25:46,2024-01-13 15:00:00,2024-01-15 07:00:00,0.0,193,17223
...,...,...,...,...,...,...,...,...,...,...
4028,0xc5df2bb6c4331898c662382fb2caf4ecde254263,BNB Chain-CoreDAO-Core Blockchain Mainnet;BNB ...,2,2023-07-07 06:49:54,2023-07-25 08:02:27,2023-07-07 06:00:00,2023-07-25 08:00:00,0.0,22,2657
4029,0xcc18bdca754f2d1e80f4f5ec22f2891abc5f05d9,BNB Chain-CoreDAO-Core Blockchain Mainnet;BNB ...,2,2023-07-07 06:19:01,2023-07-25 08:07:51,2023-07-07 06:00:00,2023-07-25 08:00:00,0.0,22,2657
4030,0xe63afa0a3b0e38f5e6a48c62195a43f8cab9bffa,BNB Chain-CoreDAO-Core Blockchain Mainnet;BNB ...,2,2023-07-07 06:38:30,2023-07-25 08:23:12,2023-07-07 06:00:00,2023-07-25 08:00:00,0.0,22,2657
4031,0xf88074f2e80e73c087b1d3f20a1e52c853daeb45,BNB Chain-CoreDAO-Core Blockchain Mainnet;BNB ...,2,2023-07-07 06:38:30,2023-07-25 08:23:12,2023-07-07 06:00:00,2023-07-25 08:00:00,0.0,22,2657
4032,0xfa0b2352dc7b5a2ecc669ca92b60da2a8442c52e,BNB Chain-CoreDAO-Core Blockchain Mainnet;BNB ...,2,2023-07-07 06:21:28,2023-07-25 08:49:50,2023-07-07 06:00:00,2023-07-25 08:00:00,0.0,22,2657

In [41]:
group_counts = mutiple_days_event_rst_df.groupby('group_id').size().reset_index(name='counts')

# 筛选出记录数小于20的分组
filtered_groups = group_counts[group_counts['counts'] < 20]
filtered_groups

Empty DataFrame
Columns: [group_id, counts]
Index: []

In [56]:
mutiple_days_event_rst_df[mutiple_days_event_rst_df['group_id']==17223]

,SENDER_WALLET,seq_N,dt_nunique,life_start_time,life_end_time,life_start_hour,life_end_hour,seq_daily_amount,final_group_size,group_id
0,0x00389e78c3c5a2c5485ba8756601c8c843126573,DFK-DeFi Kingdoms-Klaytn Mainnet Cypress;DFK-D...,2,2024-01-13 15:25:35,2024-01-15 07:48:36,2024-01-13 15:00:00,2024-01-15 07:00:00,0.0,193,17223
1,0x00f889cfaf657db097d5a16da53fbbb03515f8a8,DFK-DeFi Kingdoms-Klaytn Mainnet Cypress;DFK-D...,2,2024-01-13 15:22:25,2024-01-15 07:44:52,2024-01-13 15:00:00,2024-01-15 07:00:00,0.0,193,17223
2,0x027b9dd7b0585a769ebd133ba391afcd686d9949,DFK-DeFi Kingdoms-Klaytn Mainnet Cypress;DFK-D...,2,2024-01-13 15:00:16,2024-01-15 07:37:10,2024-01-13 15:00:00,2024-01-15 07:00:00,0.0,193,17223
3,0x0701c0a252ac5e506106f42746a68dfb6cd87e6b,DFK-DeFi Kingdoms-Klaytn Mainnet Cypress;DFK-D...,2,2024-01-13 15:23:30,2024-01-15 07:46:24,2024-01-13 15:00:00,2024-01-15 07:00:00,0.0,193,17223
4,0x07894ee788ab6666157102fc93989040990c08b3,DFK-DeFi Kingdoms-Klaytn Mainnet Cypress;DFK-D...,2,2024-01-13 15:01:17,2024-01-15 07:25:46,2024-01-13 15:00:00,2024-01-15 07:00:00,0.0,193,17223
...,...,...,...,...,...,...,...,...,...,...
188,0xf7cfb93cc7bded7e7db64ec2cdab9ec64821151c,DFK-DeFi Kingdoms-Klaytn Mainnet Cypress;DFK-D...,2,2024-01-13 15:22:43,2024-01-15 07:47:36,2024-01-13 15:00:00,2024-01-15 07:00:00,0.0,193,17223
189,0xfa9c6ed1932d85bc02746356b6e25cd47b077eb6,DFK-DeFi Kingdoms-Klaytn Mainnet Cypress;DFK-D...,2,2024-01-13 15:26:12,2024-01-15 07:49:19,2024-01-13 15:00:00,2024-01-15 07:00:00,0.0,193,17223
190,0xfad3b1739c4421bffbc3a7d1a7969013cc03a3ab,DFK-DeFi Kingdoms-Klaytn Mainnet Cypress;DFK-D...,2,2024-01-13 15:27:12,2024-01-15 07:50:28,2024-01-13 15:00:00,2024-01-15 07:00:00,0.0,193,17223
191,0xfd3f6198e0d48cac1d7c67c2a17c81db321067a3,DFK-DeFi Kingdoms-Klaytn Mainnet Cypress;DFK-D...,2,2024-01-13 15:29:08,2024-01-15 07:53:08,2024-01-13 15:00:00,2024-01-15 07:00:00,0.0,193,17223
192,0xfffe1ab67cad35286e61940785bec44ff11ce28e,DFK-DeFi Kingdoms-Klaytn Mainnet Cypress;DFK-D...,2,2024-01-13 15:20:33,2024-01-15 07:43:00,2024-01-13 15:00:00,2024-01-15 07:00:00,0.0,193,17223

In [43]:
mutiple_days_event_rst_df.groupby(['group_id']).count()

,SENDER_WALLET,seq_N,dt_nunique,life_start_time,life_end_time,life_start_hour,life_end_hour,seq_daily_amount,final_group_size
group_id,,,,,,,,,
2543,23,23,23,23,23,23,23,23,23
2570,26,26,26,26,26,26,26,26,26
2573,44,44,44,44,44,44,44,44,44
2576,24,24,24,24,24,24,24,24,24
2585,36,36,36,36,36,36,36,36,36
...,...,...,...,...,...,...,...,...,...
51371,29,29,29,29,29,29,29,29,29
52960,35,35,35,35,35,35,35,35,35
52961,30,30,30,30,30,30,30,30,30
52963,30,30,30,30,30,30,30,30,30
52964,20,20,20,20,20,20,20,20,20

# 宏观命中比例

In [54]:
%%time
# prompt: sybil_file只有一列包含女巫钱包地址的列，定义函数 check_sybil_ratio(df,sybil_file, hit_file, mismatch_file),读取输入sybil_file文件到df_blacksample,输出df中SENDER_WALLET命中sybil_file的记录数和占比，将df中命中的记录存储到hit_file,不命中的存储到mismatch_file


def filter_new_sybil(df, new_sybil_ratio):
    # 首先，计算每个 group_id 下 val1 的计数占比
    df['new_sybil_flag'] = df['_merge'].apply(lambda x: 1 if x == 'left_only' else 0)
    df['new_sybil_count'] = df.groupby('group_id')['new_sybil_flag'].transform('sum')
    df['total_count']     = df.groupby('group_id')['new_sybil_count'].transform('count')
    df['new_sybil_ratio'] = df['new_sybil_count'] / df['total_count']

    # 筛选出 val1 计数占比超过 new_sybil_ratio 的 group_id 分组
    filtered_groups = df[df['new_sybil_ratio'] > new_sybil_ratio]['group_id'].unique()

    # 使用筛选出的 group_id 分组，从原始 DataFrame 中筛选记录
    filtered_df = df[df['group_id'].isin(filtered_groups)]

    print("filtered_groups: \n",filtered_groups)
    return filtered_df


def check_sybil_ratio(df,  match_file):

  hit_count = 0
  for i in range(len(df)):
    if df.loc[i, 'SENDER_WALLET'] in df_blacksample.index:
      hit_count += 1

  hit_ratio = hit_count / len(df)

  hit_df = df[df['SENDER_WALLET'].isin(df_blacksample.index)]
  mismatch_df = df[~df['SENDER_WALLET'].isin(df_blacksample.index)]


  # 使用merge函数进行左连接，并添加一个indicator列
  match_df = df.merge(df_blacksample, left_on='SENDER_WALLET', right_index=True, how='left', indicator=True)
  # match_df = df.join(df_blacksample, how='left', on='SENDER_WALLET')
    
  final_df = filter_new_sybil(match_df, new_sybil_ratio=0.5)
  final_df.to_csv(match_file)

  print(f"Number of SENDER_WALLET mismatch: {mismatch_df.shape[0]}")
  print(f"Number of SENDER_WALLET hit: {hit_count}")
  print(f"Sybil Ratio: {hit_ratio}")

  print(f"All sybil count: {len(df)}, New sybil count: {len(final_df)}")
    
  return final_df

# def check_sybil_ratio(df, sybil_file, hit_file, mismatch_file):
#   df_blacksample = pd.read_csv(sybil_file, index_col=0)

#   hit_count = 0
#   for i in range(len(df)):
#     if df.loc[i, 'SENDER_WALLET'] in df_blacksample.index:
#       hit_count += 1

#   hit_ratio = hit_count / len(df)

#   hit_df = df[df['SENDER_WALLET'].isin(df_blacksample.index)]
#   mismatch_df = df[~df['SENDER_WALLET'].isin(df_blacksample.index)]

#   hit_df.to_csv(hit_file)
#   mismatch_df.to_csv(mismatch_file)

#   print(f"Number of SENDER_WALLET mismatch: {mismatch_df.shape[0]}")
#   print(f"Number of SENDER_WALLET hit: {hit_count}")
#   print(f"Sybil Ratio: {hit_ratio}")

#   return hit_count, hit_ratio


# check_sybil_ratio(rst_testday, 'layer0/match.csv')

# Number of SENDER_WALLET mismatch: 997
# Number of SENDER_WALLET hit: 845
# Sybil Ratio: 0.4587404994571118  未限制组内的开始结束
# (845, 0.4587404994571118)

# Number of SENDER_WALLET mismatch: 1438
# Number of SENDER_WALLET hit: 1450
# Sybil Ratio: 0.5020775623268698  1.2日
# Wall time: 657 ms
# (1450, 0.5020775623268698)

Wall time: 0 ns

In [55]:
check_sybil_ratio(mutiple_days_event_rst_df.reset_index(drop=True), 'layer0/y1_dt2_match.csv')

filtered_groups:
 [18079 37083 39688 12719 12391 18106 25628 27004 27553 12310 19935  2650
 52961 25617 25619 36004  2638 52963 50333 18071  2596 25554 24555  7658
 28959 52960 25354 25555 18087  2625  2585 18086  2573 12382 18085 52964
  2576 36003 18097  2597  2604  4949  7681 28983 21070 35607 18096  2624
 25740 25553 18114 25557 51371  2631  2570 18074  2656  2637 24542 18065
  2543  2672  2598 26919 18060  2606  2663  2652  4961 14271 11896  2657]
Number of SENDER_WALLET mismatch: 2306
Number of SENDER_WALLET hit: 1727
Sybil Ratio: 0.4282172080337218
All sybil count: 4033, New sybil count: 2335

,SENDER_WALLET,seq_N,dt_nunique,life_start_time,life_end_time,life_start_hour,life_end_hour,seq_daily_amount,final_group_size,group_id,_merge,new_sybil_flag,new_sybil_count,total_count,new_sybil_ratio
0,0x00389e78c3c5a2c5485ba8756601c8c843126573,DFK-DeFi Kingdoms-Klaytn Mainnet Cypress;DFK-D...,2,2024-01-13 15:25:35,2024-01-15 07:48:36,2024-01-13 15:00:00,2024-01-15 07:00:00,0.0,193,17223,both,0,0,193,0.000000
1,0x00f889cfaf657db097d5a16da53fbbb03515f8a8,DFK-DeFi Kingdoms-Klaytn Mainnet Cypress;DFK-D...,2,2024-01-13 15:22:25,2024-01-15 07:44:52,2024-01-13 15:00:00,2024-01-15 07:00:00,0.0,193,17223,both,0,0,193,0.000000
2,0x027b9dd7b0585a769ebd133ba391afcd686d9949,DFK-DeFi Kingdoms-Klaytn Mainnet Cypress;DFK-D...,2,2024-01-13 15:00:16,2024-01-15 07:37:10,2024-01-13 15:00:00,2024-01-15 07:00:00,0.0,193,17223,both,0,0,193,0.000000
3,0x0701c0a252ac5e506106f42746a68dfb6cd87e6b,DFK-DeFi Kingdoms-Klaytn Mainnet Cypress;DFK-D...,2,2024-01-13 15:23:30,2024-01-15 07:46:24,2024-01-13 15:00:00,2024-01-15 07:00:00,0.0,193,17223,both,0,0,193,0.000000
4,0x07894ee788ab6666157102fc93989040990c08b3,DFK-DeFi Kingdoms-Klaytn Mainnet Cypress;DFK-D...,2,2024-01-13 15:01:17,2024-01-15 07:25:46,2024-01-13 15:00:00,2024-01-15 07:00:00,0.0,193,17223,both,0,0,193,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4028,0xc5df2bb6c4331898c662382fb2caf4ecde254263,BNB Chain-CoreDAO-Core Blockchain Mainnet;BNB ...,2,2023-07-07 06:49:54,2023-07-25 08:02:27,2023-07-07 06:00:00,2023-07-25 08:00:00,0.0,22,2657,left_only,1,21,22,0.954545
4029,0xcc18bdca754f2d1e80f4f5ec22f2891abc5f05d9,BNB Chain-CoreDAO-Core Blockchain Mainnet;BNB ...,2,2023-07-07 06:19:01,2023-07-25 08:07:51,2023-07-07 06:00:00,2023-07-25 08:00:00,0.0,22,2657,left_only,1,21,22,0.954545
4030,0xe63afa0a3b0e38f5e6a48c62195a43f8cab9bffa,BNB Chain-CoreDAO-Core Blockchain Mainnet;BNB ...,2,2023-07-07 06:38:30,2023-07-25 08:23:12,2023-07-07 06:00:00,2023-07-25 08:00:00,0.0,22,2657,left_only,1,21,22,0.954545
4031,0xf88074f2e80e73c087b1d3f20a1e52c853daeb45,BNB Chain-CoreDAO-Core Blockchain Mainnet;BNB ...,2,2023-07-07 06:38:30,2023-07-25 08:23:12,2023-07-07 06:00:00,2023-07-25 08:00:00,0.0,22,2657,both,0,21,22,0.954545
4032,0xfa0b2352dc7b5a2ecc669ca92b60da2a8442c52e,BNB Chain-CoreDAO-Core Blockchain Mainnet;BNB ...,2,2023-07-07 06:21:28,2023-07-25 08:49:50,2023-07-07 06:00:00,2023-07-25 08:00:00,0.0,22,2657,left_only,1,21,22,0.954545

In [47]:
import pandas as pd

Empty DataFrame
Columns: [group_id, col1, val1_count, total_count, val1_ratio]
Index: []

In [ ]:
# from google.colab import drive
# drive.mount('/content/drive')